image: archlinux
packages:
- rustup
repositories: {}
shell: false
sources:
  - https://github.com/hackagotchi/hcor
tasks:
- setup: |
    rustup toolchain install nightly
    cd hcor/
    rustup run nightly cargo fetch
- nightly: |
    rustup default nightly
    cd hcor/
    cargo build
    cargo test
- fmt: |
    cargo fmt -- --check
