image: archlinux
packages:
- rustup
repositories: {}
shell: false
sources:
  - https://github.com/hackagotchi/hcor
secrets:
  - 2c543725-886e-43b5-9b10-80c8131a621d
tasks:
- setup: |
    rustup toolchain install nightly
    cd hcor/
    rustup run nightly cargo fetch
    cp ~/.env .
- nightly: |
    rustup default nightly
    cd hcor/
    cargo build
    cargo test
- fmt: |
    cargo fmt -- --check
